#include lib/item_deck

--------------------------------------------------------------------------------
-- Draws a 2h toy card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function draw2hToyCard(playerColor)
  item_deck.drawFromItemDeck(playerColor, "2nd_hand_toy_", "second hand toy")
end

function onDrop(playerColor)
  draw2hToyCard(playerColor)
end
