#include lib/item_deck

--------------------------------------------------------------------------------
-- Draws a dog leash card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function drawDogLeashCard(playerColor)
  item_deck.drawFromItemDeck(playerColor, "dog_leash_", "dog leash")
end

function onDrop(playerColor)
  drawDogLeashCard(playerColor)
end
