#include lib/purchase_button

--------------------------------------------------------------------------------
-- Creates a custom button.
--------------------------------------------------------------------------------
function onLoad()
  purchase_button.onLoad()
end

--------------------------------------------------------------------------------
-- Handler for click, invoked when the custom button is clicked.
--
-- @param obj The Object the button is attached to.
-- @param color Player Color of the player that pressed the button.
-- @param alt_click True if a button other than left-click was used to click the
--        button.
--------------------------------------------------------------------------------
function click_function(obj, color, alt_click)
  purchase_button.click_function(obj, color, alt_click, "elizabethan_collar_",
                                 "Elizabethan collar")
end
