#include lib/item_deck

--------------------------------------------------------------------------------
-- Draws a Elizabethan collar card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function draw2hToyCard(playerColor)
  item_deck.purchaseFromItemDeck(playerColor, "elizabethan_collar_", "Elizabethan collar")
end

function onDrop(playerColor)
  draw2hToyCard(playerColor)
end
