log_utils = {}
logStyle("info", "Grey", string.format("[%.9f INFO]", Time.time), "")
logStyle("warning", "Yellow", string.format("[%.9f WARN]", Time.time), "")

--------------------------------------------------------------------------------
-- Logs a message to console with `info` style.
--
-- @param logMessage The log message.
--------------------------------------------------------------------------------
function log_utils.info(logMessage)
  log(logMessage, nil, "info")
end

--------------------------------------------------------------------------------
-- Logs a message to console with `warning` style.
--
-- @param logMessage The log message.
--------------------------------------------------------------------------------
function log_utils.warn(logMessage)
  log(logMessage, nil, "warning")
end
