logUtils = {}
logStyle("info", "Grey", string.format("[%.9f INFO]", Time.time), "")

--------------------------------------------------------------------------------
-- Logs a message to console with `info` style.
--
-- @param logMessage The log message.
--------------------------------------------------------------------------------
function logUtils.info(logMessage)
  log(logMessage, nil, "info")
end
