#include lib/item_deck

--------------------------------------------------------------------------------
-- Draws a lucky cookie card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function draw2hToyCard(playerColor)
  item_deck.drawFromItemDeck(playerColor, "lucky_cookie_", "lucky cookie")
end

function onDrop(playerColor)
  draw2hToyCard(playerColor)
end
