#include lib/item_deck

--------------------------------------------------------------------------------
-- Draws a poop bag card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function drawPoopBagCard(playerColor)
  item_deck.drawFromItemDeck(playerColor, "poop_bag_", "poop bag")
end

function onDrop(playerColor)
  drawPoopBagCard(playerColor)
end
