#include item_deck

--------------------------------------------------------------------------------
-- Draws a secret to card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function drawPreventionPillsCard(playerColor)
  item_deck.purchaseFromItemDeck(playerColor, "prevention_pills_", "prevention pills")
end

function onDrop(playerColor)
  drawPreventionPillsCard(playerColor)
end
