#include lib/item_deck

--------------------------------------------------------------------------------
-- Draws a secret card from the item deck if available.
--
-- @param playerColor Color of the player trying to draw the card.
--------------------------------------------------------------------------------
function drawSecretToyCard(playerColor)
  item_deck.purchaseFromItemDeck(playerColor, "secret_toy_", "secret toy")
end

function onDrop(playerColor)
  drawSecretToyCard(playerColor)
end
