#include shared_def

item_card = {}
--------------------------------------------------------------------------------
-- Removes tag `in_hand` from the card being played.
--
-- @param card Card being played by player `playerColor`.
-- @param playerColor Color of the player playing the card.
--------------------------------------------------------------------------------
function item_card.onCardPlay(card, playerColor)
  card.removeTag(shared_def.tag_in_hand)
  print("Player " .. playerColor .. " played " .. card.getName())
end

--------------------------------------------------------------------------------
-- Adds tag `in_hand` to the card being dealt to player.
--
-- @param card Card being played by player `playerColor`.
--------------------------------------------------------------------------------
function item_card.onCardDeal(card)
  card.addTag(shared_def.tag_in_hand)
  print("Card "..card.getName().." is played.")
end
